CREATE TABLE `ask` (
	`ask_no` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`ask_title` VARCHAR(5000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`user_id` VARCHAR(5000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`made_content` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ask_sol` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ask_sing` VARCHAR(5000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ask_status` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ask_day` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`made_date` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ask_no`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

